Add support for multiple pMapSkips
sindresorhus/p-map pull request #52
Opened 2021-09-30 05:36 UTC by ferrinweb

like this:
```javascript
console.log(await pMap([1, pMapSkip, 2,p MapSkip ,3], async value => value)) // [1, 2, 3]
```

2021-10-03 05:57 UTC, sindresorhus commented
@huntharo Would you be willing to help review?

2021-10-04 15:01 UTC, huntharo requested changes
I think we need to address the `O(n^2)` complexity on the number of `pMapSkip` items and fix the existing performance issue with the usage of `.splice()` in a loop.

I left an example of how to test the performance and how to change the `.unshift()` usage back to `.push()` with a loop that does a `.pop()` (using the array as a `O(1)` stack).  The only remaining work would be to implement the `super splice` loop that loops through `result` only a single time and touches each item only a single time.

2021-10-05 03:34 UTC, ferrinweb commented on index.js
> +						skippedIndexes.unshift(index);
Thanks!
I made improvements in the latest commit.
Help review, please!

2021-10-05 03:34 UTC, ferrinweb commented on index.js
> +						skippedIndexes.unshift(index);
Thanks!
I made improvements in the latest commit.
Help review, please!

2021-10-05 03:44 UTC, ferrinweb commented on test.js
> +test('multiple pMapSkips', async t => {
Added.

2021-11-02 12:03 UTC, merged

2021-11-02 12:03 UTC, sindresorhus commented
Thanks :)